# Generated by Django 2.2.10 on 2020-04-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(editable=False, verbose_name='Нормальный url')),
                ('order', models.IntegerField(verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('slug', models.SlugField(editable=False, verbose_name='Нормальный url')),
                ('order', models.IntegerField(verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('formulation', models.TextField(verbose_name='Формулировка')),
                ('order', models.IntegerField(verbose_name='Порядок вывода')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pythoncourses.Lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(editable=False, verbose_name='Нормальный url')),
                ('order', models.IntegerField(verbose_name='Порядок вывода')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pythoncourses.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_put', models.TextField(verbose_name='Входные данные')),
                ('out_put', models.TextField(verbose_name='Выходные данные')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pythoncourses.Task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pythoncourses.Theme', verbose_name='Тема'),
        ),
    ]
