# Generated by Django 2.2.10 on 2020-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythoncourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(verbose_name='Нормальный url'),
        ),
    ]
