# Generated by Django 2.2.10 on 2020-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythoncourses', '0002_auto_20200424_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Нормальный url'),
        ),
    ]
