# Generated by Django 2.2.10 on 2020-04-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythoncourses', '0003_auto_20200424_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
